on:
  schedule:
  - cron: "0 0 * * *"

name: build_data

jobs:
  build_data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Faker pandas
          
      - name: Generate Fake Data
        run: python health_data/generate_data.py

      - name: Push the new file to the repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add health_data/covid_19_results.csv
          git commit -m "GH ACTION - COVID 19 Results"
          git push -q
